### ISSUE TITLE
Initialize project

### ISSUE THREAD

**Issue by przemgk** [przemgk/Frontend-Mentor-CH16#1]
**Tasks to do:**
- [x] Create repository
- [x] Create project structure
- [x] Set Gulp for automation
- [x] Write initial styles and add css reset
- [x] Setup Continuous Deployment
