### ISSUE TITLE
Write HTML structure and style website

### ISSUE THREAD

**Issue by przemgk** [przemgk/Frontend-Mentor-CH16#2]
**Tasks to do:**
- [x] Create version for mobile devices
- [x] Create version for desktop
- [x] Add toggle prices
